# Generated by Django 3.2.4 on 2021-06-27 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stacks_Database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='some string', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword_Definition_Dictionary',
            fields=[
                ('stacks_database_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='front.stacks_database')),
                ('keyword', models.TextField(default='No keywords')),
                ('definition', models.TextField(default='No definitions')),
                ('difficulty', models.TextField(default='No difficulties')),
            ],
            bases=('front.stacks_database',),
        ),
    ]
